image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Python project with dependencies
    # Do not use `python -m pip install` with pyenv,
    # see https://github.com/pyenv/pyenv/issues/2243
    init: |
      pip install -r requirements.txt
      pushd data \
        && curl -O https://openrepair.org/wp-content/uploads/2023/02/OpenRepairData_v0.3_aggregate_202210.zip \
        && unzip OpenRepairData_v0.3_aggregate_202210.zip \
        && popd
      gp sync-done dependencies

  - name: Launch JupyterLab
    init: |
      gp sync-await dependencies
    # Inspiration: https://github.com/jupyterlab/jupyterlab/blob/a920f33/.gitpod.yml
    # and https://github.com/gitpod-io/gitpod/issues/16306
    command: |
      jupyter lab --port 8888 \
        --ServerApp.token='' \
        --ServerApp.allow_remote_access=true \
        --no-browser

ports:
  - port: 8888
